"""Shared constants for lmctl."""

APP_NAME = "lmctl"
KEYRING_SERVICE = APP_NAME
USERNAME_ENV_VARS = ("LMCTL_USERNAME", "LAMARZOCCO_USERNAME")
PASSWORD_ENV_VARS = ("LMCTL_PASSWORD", "LAMARZOCCO_PASSWORD")
USERNAME_KEY = "username"
DEFAULT_SERIAL_KEY = "default_serial"
