[project]
name = "lmctl"
version = "0.1.0"
description = "Command-line interface for pylamarzocco"
readme = "README.md"
authors = [
    { name = "Michael Recachinas", email = "mrecachinas@github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.5",
    "keyring>=25.7.0",
    "pylamarzocco>=2.2.4",
]

[project.scripts]
lmctl = "lmctl.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "ty>=0.0.35",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--basetemp=.pytest-tmp",
]
testpaths = ["tests"]
